name: Build, Test, and Publish node-installer image

on:
  workflow_call:
    inputs:
      ref:
        description: 'the git ref for the associated workflow'
        type: string
        required: true

jobs:
  # Note: assumes being called in a workflow where build has already run and
  # required artifacts have been uploaded
  build-test-publish:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set RELEASE_VERSION env var
        run: |
          if [[ "${{ startsWith(inputs.ref, 'refs/tags/v')}}" == "true" ]]; then
            echo "RELEASE_VERSION=$(echo -n ${{ inputs.ref }} | cut -d '/' -f 3)" >> $GITHUB_ENV
          else
            echo "RELEASE_VERSION=$(date +%Y%m%d-%H%M%S)-g$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          fi

      - uses: actions/download-artifact@v4
        with:
          path: _artifacts

      # Setup buildx to build multiarch image: https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      # Build and extract node-installer image
      - name: Extract musl artifacts into ./node-installer/.tmp/linux/(amd64|arm64) dir
        run: |
          mkdir -p ./node-installer/.tmp/linux/amd64
          mkdir -p ./node-installer/.tmp/linux/arm64
          for f in ./_artifacts/*/*-x86_64.tar.gz; do tar -xf $f --directory ./node-installer/.tmp/linux/amd64; done
          for f in ./_artifacts/*/*-aarch64.tar.gz; do tar -xf $f --directory ./node-installer/.tmp/linux/arm64; done

      # Build local image for testing
      - name: Build node-installer image for testing
        run: make build-dev-installer-image
        working-directory: node-installer

      # Install kind for integration testing
      - name: Install kind
        uses: helm/kind-action@v1.12.0
        with:
          install_only: true
          
      # Run the integration test
      - name: Run integration test
        run: ./integration-test.sh
        working-directory: node-installer

      # Login to registry and publish if tests pass
      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push node-installer image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/node-installer:${{ env.RELEASE_VERSION }}
          context: node-installer
          platforms: linux/amd64,linux/arm64

      - name: Clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json
