name: Publish node-installer image

on:
  workflow_call:
    inputs:
      ref:
        description: 'the git ref for the associated workflow'
        type: string
        required: true

jobs:
  # Note: assumes being called in a workflow where build has already run and
  # required artifacts have been uploaded
  publish:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set RELEASE_VERSION env var
        run: |
          if [[ "${{ startsWith(inputs.ref, 'refs/tags/v')}}" == "true" ]]; then
            echo "RELEASE_VERSION=$(echo -n ${{ inputs.ref }} | cut -d '/' -f 3)" >> $GITHUB_ENV
          else
            echo "RELEASE_VERSION=$(date +%Y%m%d-%H%M%S)-g$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          fi

      - uses: actions/download-artifact@v4
        with:
          path: _artifacts

      # Setup buildx to build multiarch image: https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: setup buildx
        uses: docker/setup-buildx-action@v3

      - name: login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push node-installer image
      # TODO: remove once https://github.com/spinkube/runtime-class-manager handles this
      - name: untar musl artifacts into ./node-installer/.tmp/linux/(amd64|arm64) dir
        run: |
          mkdir -p ./node-installer/.tmp/linux/amd64
          mkdir -p ./node-installer/.tmp/linux/arm64
          for f in ./_artifacts/*/*-x86_64.tar.gz; do tar -xf $f --directory ./node-installer/.tmp/linux/amd64; done
          for f in ./_artifacts/*/*-aarch64.tar.gz; do tar -xf $f --directory ./node-installer/.tmp/linux/arm64; done

      - name: build and push node-installer image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/node-installer:${{ env.RELEASE_VERSION }}
          context: node-installer
          platforms: linux/amd64,linux/arm64

      - name: clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json
